name = "seocrawler-web"
compatibility_date = "2024-04-14"
main = "src/worker.ts"

[env.production]
vars = { APP_URL = "https://seocrawler-web.curtisworkers.workers.dev" }

[[d1_databases]]
binding = "DB"
database_name = "seocrawler-db"
database_id = "35f3b153-fb3b-4d7d-8ad3-87e98044a969"

[[r2_buckets]]
binding = "REPORTS"
bucket_name = "seocrawler-reports"